---
# tasks file for wordpress

  - name: Download WordPress
    get_url:
      url=https://wordpress.org/latest.tar.gz
      dest=/tmp/wordpress.tar.gz
      validate_certs=no

  - name: Extract WordPress
    unarchive:
      src=/tmp/wordpress.tar.gz
      dest=/var/www/
      copy=no
      owner=apache
      group=apache
      mode=0775

  - name: Update default Apache site
    lineinfile:
      dest=/etc/httpd/conf/httpd.conf
      regexp="(.)+DocumentRoot /var/www/html"
      line="DocumentRoot /var/www/wordpress"

  - name: Copy sample config file
    command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

  - name: Ensure directories are 0755
    file:
      dest=/var/www
      owner=apache
      group=apache
      mode=0775
      recurse=yes

  - name: Update WordPress config file
    lineinfile:
      dest=/var/www/wordpress/wp-config.php
      regexp="{{ item.regexp }}"
      line="{{ item.line }}"
    with_items:
      - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', 'wordpress');"}
      - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', 'wordpress');"}
      - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', 'password');"}
      - {'regexp': "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', '{{ ansible_default_ipv4.address }}');"}

  - name: http service state
    service: name=httpd state=restarted
